(function(){
  if(window.__guideExcursionCatalogInstalled)return;
  window.__guideExcursionCatalogInstalled='EX2';
  function q(s,r){return (r||document).querySelector(s);}function qa(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s));}
  var recs=[
    {rx:/Курш|Высот[аы] Эфа|Танцующ/i,title:'Экскурсии на Куршскую косу из Зеленоградска',meta:'несколько гидов и форматов · выбирайте вариант со свободной датой',url:'https://experience.tripster.ru/experience/Zelenogradsk/20281-kurshskaya-kosa/'},
    {rx:/Балтийск|Янтарн|Филинск|Западное побережье|Светлогорск/i,title:'Экскурсии по западному побережью из Зеленоградска',meta:'Балтийск, Янтарный, Светлогорск · выбирайте доступный вариант',url:'https://experience.tripster.ru/experience/Zelenogradsk/96731-svetlogorsk/'},
    {rx:/Зеленоградск/i,title:'Экскурсии по Зеленоградску',meta:'пешком, с детьми и в мини-группах · смотрите свободные даты',url:'https://experience.tripster.ru/experience/Zelenogradsk/'},
    {rx:/Калининград|Канта|К[её]нигсберг|Рыбн|форт|Д[её]нхофф|Амалиенау/i,title:'Экскурсии по Калининграду',meta:'обзорные и тематические маршруты · выбирайте по свободным датам',url:'https://experience.tripster.ru/experience/Kaliningrad/'}
  ];
  function pick(card){var text=card.innerText||'';if(/День приезда|День вылета|День отъезда/i.test(text))return null;for(var i=0;i<recs.length;i++)if(recs[i].rx.test(text))return recs[i];return null;}
  function addDayCards(){qa('.day').forEach(function(card){var old=q('.guide-day-excursion',card),r=pick(card);if(!r){if(old)old.remove();return;}if(old&&old.dataset.url===r.url)return;if(old)old.remove();var box=document.createElement('div');box.className='guide-day-excursion';box.dataset.url=r.url;box.innerHTML='<div class="guide-day-excursion-kicker">Экскурсия по теме дня</div><b>'+r.title+'</b><span>'+r.meta+'</span><a href="'+r.url+'" target="_blank" rel="noopener" data-tripster-catalog>Подобрать доступную экскурсию</a>';var head=q('.day-head',card);if(head&&head.nextSibling)card.insertBefore(box,head.nextSibling);else card.insertBefore(box,card.firstChild);});}
  function ticketUrl(card){var t=card.innerText||'';if(/Янтарь-холл|Кадышев|Банкет/i.test(t))return'https://yantarkassa.ru/events';if(/Светлогорск|Индия звучащая|фитнес-танцы/i.test(t))return'https://www.svetlogorsk-tourism.ru/calendar/';return'https://visit-kaliningrad.ru/events/';}
  function addEventLinks(){qa('.event-card').forEach(function(card){if(q('.guide-event-ticket-link',card))return;var a=document.createElement('a');a.className='guide-event-ticket-link';a.href=ticketUrl(card);a.target='_blank';a.rel='noopener';a.textContent='Билеты / подробнее';var actions=q('.event-actions',card);if(actions)actions.insertBefore(a,actions.firstChild);else card.appendChild(a);});}
  function cleanLegacy(){qa('.day .event-recommendation').forEach(function(x){x.style.display='none';});}
  function refresh(){try{cleanLegacy();addDayCards();addEventLinks();}catch(e){console.error('EX2',e);}}
  var stl=document.createElement('style');stl.id='guide-excursion-catalog-style';stl.textContent='.guide-day-excursion{margin:0 16px 12px;padding:13px;border:1px solid var(--line,#ddd);border-radius:14px;background:#f7faf9}.guide-day-excursion-kicker{font-size:10px;text-transform:uppercase;letter-spacing:.05em;color:var(--accent,#2f7d78);font-weight:850;margin-bottom:4px}.guide-day-excursion>b{display:block;font-size:15px;line-height:1.3}.guide-day-excursion>span{display:block;margin-top:4px;color:var(--muted,#777);font-size:11px}.guide-day-excursion>a,.guide-event-ticket-link{display:block;margin-top:10px;padding:10px 11px;border-radius:11px;background:var(--accent,#2f7d78);color:#fff!important;text-align:center;text-decoration:none!important;font-weight:850}.event-actions .guide-event-ticket-link{margin-top:0}.day .event-recommendation{display:none!important}@media(max-width:520px){.event-actions{grid-template-columns:1fr!important}}';if(!q('#'+stl.id))document.head.appendChild(stl);
  document.addEventListener('click',function(e){var t=e.target;if(t&&(t.id==='next'||(t.dataset&&['days','events'].indexOf(t.dataset.tab)>=0)))setTimeout(refresh,180);},true);[700,1400,2600].forEach(function(ms){setTimeout(refresh,ms);});window.guideRefreshExcursionCatalog=refresh;
})();