(function(){
  'use strict';
  if(window.__guideSingleWeatherInstalled)return;
  window.__guideSingleWeatherInstalled='WX6';
  var cityLoc={'Калининград':[54.7104,20.5100,false],'Зеленоградск':[54.9600,20.4750,true],'Светлогорск':[54.9430,20.1510,true],'Пионерский':[54.9510,20.2270,true],'Янтарный':[54.8710,19.9400,true],'Балтийск':[54.6530,19.9080,true],'Гусев':[54.5922,22.1997,false]};
  var seaLoc={'Зеленоградск':[54.970,20.360],'Светлогорск':[54.950,20.080],'Пионерский':[54.955,20.185],'Янтарный':[54.880,19.860],'Балтийск':[54.660,19.800]};
  var cache={};
  function q(s,r){return(r||document).querySelector(s);}function qa(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s));}
  function pad(n){return String(n).padStart(2,'0');}function iso(d){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());}
  function cards(){var x=qa('#planList .day');return x.length?x:qa('.day');}
  function tripDates(){var state=(typeof st!=='undefined'&&st)||{},a=(q('#a')&&q('#a').value)||state.start||'',b=(q('#b')&&q('#b').value)||state.end||'';if(!a||!b)return[];var out=[],d=new Date(a+'T12:00:00'),e=new Date(b+'T12:00:00'),g=0;while(d<=e&&g++<31){out.push(iso(d));d.setDate(d.getDate()+1);}return out;}
  function titleOf(card){var h=q('.day-head h3',card)||q('.day-head h2',card);return(h&&h.textContent||'').trim();}
  function cityFromProgram(card){var t=titleOf(card);if(/Янтарн/i.test(t))return'Янтарный';if(/Светлогорск|Раушен/i.test(t))return'Светлогорск';if(/Пионерск/i.test(t))return'Пионерский';if(/Балтийск/i.test(t))return'Балтийск';if(/Гусев/i.test(t))return'Гусев';if(/Курш|Высот[аы] Эфа|Танцующ|Рыбач/i.test(t))return'Зеленоградск';if(/Филинск|Западное побережье/i.test(t))return'Светлогорск';if(/Зеленоградск/i.test(t))return'Зеленоградск';if(/Амалиенау|проспект Мира|зоопарк|форт|Д[её]нхофф|Штайн|Кант|К[её]нигсберг|Рыбн|Музей Мирового океана|Калининград/i.test(t))return'Калининград';return'';}
  function cityFor(i,card){var fromProgram=cityFromProgram(card);if(fromProgram)return fromProgram;var c=(window.planBases&&window.planBases[i])||'',s=(window.currentPlan&&window.currentPlan[i])||{};c=c||s.__boundaryCity||s.base||'';if(cityLoc[c])return c;var txt=(card&&card.innerText)||'';return Object.keys(cityLoc).find(function(x){return txt.indexOf(x)>=0;})||'Калининград';}
  function weatherText(c){if(c===0)return'ясно';if(c<=3)return'облачно';if(c===45||c===48)return'туман';if(c>=51&&c<=67)return'дождь';if(c>=80&&c<=82)return'ливни';if(c>=95)return'гроза';return'переменная погода';}
  function seaText(h){if(h==null)return'нет данных';if(h<0.45)return'спокойное';if(h<0.9)return'небольшая волна';if(h<1.5)return'волнуется';return'сильная волна';}
  function daily(j,date){if(!j||!j.daily)return null;var i=j.daily.time.indexOf(date);return i<0?null:{code:j.daily.weather_code[i],max:j.daily.temperature_2m_max[i],min:j.daily.temperature_2m_min[i],rain:j.daily.precipitation_probability_max[i]};}
  function marine(j,date){if(!j||!j.hourly)return null;var ts=[],ws=[];for(var i=0;i<j.hourly.time.length;i++){if(j.hourly.time[i].slice(0,10)!==date)continue;var t=j.hourly.sea_surface_temperature&&j.hourly.sea_surface_temperature[i],w=j.hourly.wave_height&&j.hourly.wave_height[i];if(t!=null)ts.push(t);if(w!=null)ws.push(w);}return{temp:ts.length?ts.reduce(function(a,b){return a+b;},0)/ts.length:null,wave:ws.length?ws.reduce(function(a,b){return a+b;},0)/ws.length:null};}
  function loadCity(city){if(cache[city])return cache[city];var p=cityLoc[city]||cityLoc['Калининград'];var wu='https://api.open-meteo.com/v1/forecast?latitude='+p[0]+'&longitude='+p[1]+'&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=Europe%2FKaliningrad&forecast_days=16';var wp=fetch(wu).then(function(r){return r.ok?r.json():null;}).catch(function(){return null;});var sp=Promise.resolve(null);if(p[2]&&seaLoc[city]){var s=seaLoc[city],su='https://marine-api.open-meteo.com/v1/marine?latitude='+s[0]+'&longitude='+s[1]+'&hourly=sea_surface_temperature,wave_height&timezone=Europe%2FKaliningrad&forecast_days=8&cell_selection=sea';sp=fetch(su).then(function(r){return r.ok?r.json():null;}).catch(function(){return null;});}cache[city]=Promise.all([wp,sp]).then(function(v){return{weather:v[0],marine:v[1],coastal:p[2]};});return cache[city];}
  function isInsideLive(el){return !!(el&&el.closest&&el.closest('.guide-live-weather'));}
  function legacyCandidates(card){return qa('div,section',card).filter(function(el){if(isInsideLive(el))return false;var t=(el.innerText||'').replace(/\s+/g,' ').trim();var headed=/ПОГОДА/i.test(t)&&(/Прогноз ближе к дате/i.test(t)||/температура появится с прогнозом/i.test(t));var orphan=/ВОДА/i.test(t)&&/МОРЕ/i.test(t)&&(/температура появится с прогнозом/i.test(t)||/волна появится с прогнозом/i.test(t));return headed||orphan;}).sort(function(a,b){return(a.innerText||'').length-(b.innerText||'').length;});}
  function removeLegacy(card){var list=legacyCandidates(card),removed=[];list.forEach(function(el){if(!el.isConnected||isInsideLive(el))return;if(removed.some(function(p){return p.contains&&p.contains(el);})){return;}removed.push(el);el.remove();});}
  function render(card,date,city,bundle){if(!card||!card.isConnected)return;var w=daily(bundle.weather,date);if(!w)return;var m=marine(bundle.marine,date),box=q('.guide-live-weather',card)||document.createElement('div');box.className='guide-live-weather';var sea='';if(bundle.coastal){var temp=m&&m.temp!=null?m.temp.toFixed(1)+'°':'—',wave=m&&m.wave!=null?m.wave.toFixed(1)+' м':'—';sea='<div><span>Вода</span><b>'+temp+'</b><small>'+(m&&m.temp!=null?'Балтийское море':'нет данных')+'</small></div><div><span>Море</span><b>'+seaText(m&&m.wave)+'</b><small>'+wave+'</small></div>';}
    box.innerHTML='<div class="guide-weather-title">ПОГОДА</div><div class="guide-weather-grid"><div><span>Воздух</span><b>'+Math.round(w.min)+'…'+Math.round(w.max)+'°</b><small>'+weatherText(w.code)+'</small></div><div><span>Осадки</span><b>'+(w.rain==null?'—':Math.round(w.rain)+'%')+'</b><small>вероятность</small></div>'+sea+'</div>';
    if(!box.parentNode){var anchor=q('.day-head',card);if(anchor&&anchor.nextSibling)card.insertBefore(box,anchor.nextSibling);else card.insertBefore(box,card.firstChild);}removeLegacy(card);card.dataset.guideWeatherKey=date+'|'+city;card.dataset.guideWeatherDate=date;card.dataset.guideWeatherCity=city;
  }
  var refreshSeq=0;
  function refresh(){var seq=++refreshSeq,cs=cards(),ds=tripDates();if(!cs.length||!ds.length)return;cs.forEach(function(card,i){var date=ds[i];if(!date)return;var city=cityFor(i,card),key=date+'|'+city;if(card.dataset.guideWeatherKey===key&&q('.guide-live-weather',card)){removeLegacy(card);return;}loadCity(city).then(function(bundle){if(seq>refreshSeq+5)return;var now=cards()[i];if(!now)return;var nowCity=cityFor(i,now),nowDate=tripDates()[i];if(nowDate!==date||nowCity!==city)return;render(now,date,city,bundle);});});}
  var timer=0;function schedule(delay){clearTimeout(timer);timer=setTimeout(refresh,typeof delay==='number'?delay:120);}
  function attachObserver(){var root=q('#planList')||q('[data-tab-panel="days"]')||q('.plan-list');if(!root||root.__guideWeatherObserved)return false;root.__guideWeatherObserved=true;new MutationObserver(function(muts){var external=muts.some(function(m){return Array.prototype.some.call(m.addedNodes||[],function(n){return !(n.nodeType===1&&n.classList&&n.classList.contains('guide-live-weather'));});});if(external)schedule(140);}).observe(root,{childList:true,subtree:true});return true;}
  var stl=document.createElement('style');stl.id='guide-single-weather-style';stl.textContent='.guide-live-weather{margin:12px 16px;padding:12px 0;border-top:1px solid var(--line,#ddd);border-bottom:1px solid var(--line,#ddd)}.guide-weather-title{font-size:11px;font-weight:850;color:var(--muted,#777);letter-spacing:.05em;margin-bottom:8px}.guide-weather-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.guide-weather-grid span{display:block;font-size:10px;text-transform:uppercase;color:var(--muted,#777);margin-bottom:3px}.guide-weather-grid b{display:block;font-size:15px}.guide-weather-grid small{display:block;font-size:10px;color:var(--muted,#777);margin-top:2px}@media(max-width:560px){.guide-weather-grid{grid-template-columns:repeat(2,minmax(0,1fr));row-gap:11px}}';if(!q('#'+stl.id))document.head.appendChild(stl);
  document.addEventListener('click',function(e){var t=e.target;if(t&&(t.id==='next'||(t.dataset&&t.dataset.tab==='days')||(t.tagName==='BUTTON'&&/Заменить/i.test(t.textContent||''))))schedule(250);},true);
  document.addEventListener('change',function(e){var t=e.target;if(t&&t.closest&&t.closest('.day'))schedule(180);},true);
  var tries=0;(function boot(){attachObserver();schedule(40);if(++tries<20)setTimeout(boot,400);})();[1200,2600,5000,9000].forEach(function(ms){setTimeout(refresh,ms);});window.guideRefreshSingleWeather=refresh;
})();